(define-key evil-normal-state-map "H" 'evil-first-non-blank)
(define-key evil-normal-state-map "L" 'evil-end-of-line)
(define-key evil-normal-state-map "J" 'centaur-tabs-backward-tab)
(define-key evil-normal-state-map "K" 'centaur-tabs-forward-tab)
(define-key evil-normal-state-map (kbd "C-w") 'kill-this-buffer)
(define-key evil-normal-state-map (kbd "M-h") 'windmove-left)
(define-key evil-normal-state-map (kbd "M-j") 'windmove-down)
(define-key evil-normal-state-map (kbd "M-k") 'windmove-up)
(define-key evil-normal-state-map (kbd "M-l") 'windmove-right)
(evil-mode t)
